[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
chrono = { workspace = true }
chrono-tz = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = "1.4"
uuid = { workspace = true }
